import type { Job, Node, Queue, ClusterStats, JobStats, ResourceUtilization } from '../types/pbs';

export const mockJobs: Job[] = [
  {
    id: '1234.server',
    name: 'simulation_job',
    user: 'user1',
    status: 'R',
    queue: 'workq',
    nodes: 2,
    cpus: 16,
    memory: '32GB',
    walltime: '24:00:00',
    elapsedTime: '12:30:45',
    submissionTime: '2026-01-23T08:00:00Z',
    startTime: '2026-01-23T08:05:00Z',
  },
  {
    id: '1235.server',
    name: 'data_analysis',
    user: 'user2',
    status: 'Q',
    queue: 'workq',
    nodes: 1,
    cpus: 8,
    memory: '16GB',
    walltime: '12:00:00',
    elapsedTime: '00:00:00',
    submissionTime: '2026-01-23T10:00:00Z',
  },
  {
    id: '1236.server',
    name: 'ml_training',
    user: 'user3',
    status: 'R',
    queue: 'gpu',
    nodes: 1,
    cpus: 32,
    memory: '64GB',
    walltime: '48:00:00',
    elapsedTime: '06:15:30',
    submissionTime: '2026-01-23T06:00:00Z',
    startTime: '2026-01-23T06:10:00Z',
  },
];

export const mockNodes: Node[] = [
  {
    id: 'node001',
    name: 'compute-node-001',
    state: 'busy',
    totalCpus: 32,
    usedCpus: 16,
    totalMemory: '128GB',
    usedMemory: '64GB',
    jobs: ['1234.server'],
    properties: ['haswell', 'infiniband'],
  },
  {
    id: 'node002',
    name: 'compute-node-002',
    state: 'free',
    totalCpus: 32,
    usedCpus: 0,
    totalMemory: '128GB',
    usedMemory: '0GB',
    jobs: [],
    properties: ['haswell', 'infiniband'],
  },
  {
    id: 'node003',
    name: 'compute-node-003',
    state: 'busy',
    totalCpus: 32,
    usedCpus: 32,
    totalMemory: '128GB',
    usedMemory: '96GB',
    jobs: ['1236.server'],
    properties: ['skylake', 'gpu'],
  },
  {
    id: 'node004',
    name: 'compute-node-004',
    state: 'down',
    totalCpus: 32,
    usedCpus: 0,
    totalMemory: '128GB',
    usedMemory: '0GB',
    jobs: [],
    properties: ['haswell'],
  },
];

export const mockQueues: Queue[] = [
  {
    name: 'workq',
    enabled: true,
    started: true,
    totalJobs: 45,
    runningJobs: 30,
    queuedJobs: 15,
    maxRunning: 50,
    priority: 100,
  },
  {
    name: 'gpu',
    enabled: true,
    started: true,
    totalJobs: 12,
    runningJobs: 8,
    queuedJobs: 4,
    maxRunning: 10,
    priority: 150,
  },
  {
    name: 'express',
    enabled: true,
    started: true,
    totalJobs: 5,
    runningJobs: 3,
    queuedJobs: 2,
    priority: 200,
  },
];

export const mockClusterStats: ClusterStats = {
  totalNodes: 4,
  busyNodes: 2,
  freeNodes: 1,
  downNodes: 1,
  totalJobs: 62,
  runningJobs: 41,
  queuedJobs: 21,
  totalCpus: 128,
  usedCpus: 48,
  cpuUtilization: 37.5,
};

export const mockJobStats: JobStats[] = [
  { timestamp: '00:00', totalJobs: 50, runningJobs: 35, queuedJobs: 15, completedJobs: 120, failedJobs: 2 },
  { timestamp: '04:00', totalJobs: 55, runningJobs: 38, queuedJobs: 17, completedJobs: 125, failedJobs: 2 },
  { timestamp: '08:00', totalJobs: 60, runningJobs: 40, queuedJobs: 20, completedJobs: 130, failedJobs: 3 },
  { timestamp: '12:00', totalJobs: 65, runningJobs: 42, queuedJobs: 23, completedJobs: 135, failedJobs: 3 },
  { timestamp: '16:00', totalJobs: 62, runningJobs: 41, queuedJobs: 21, completedJobs: 140, failedJobs: 3 },
  { timestamp: '20:00', totalJobs: 58, runningJobs: 39, queuedJobs: 19, completedJobs: 145, failedJobs: 4 },
];

export const mockResourceUtilization: ResourceUtilization[] = [
  { timestamp: '00:00', cpuUtilization: 35, memoryUtilization: 40, nodeUtilization: 45 },
  { timestamp: '04:00', cpuUtilization: 38, memoryUtilization: 42, nodeUtilization: 48 },
  { timestamp: '08:00', cpuUtilization: 42, memoryUtilization: 45, nodeUtilization: 50 },
  { timestamp: '12:00', cpuUtilization: 45, memoryUtilization: 48, nodeUtilization: 55 },
  { timestamp: '16:00', cpuUtilization: 40, memoryUtilization: 45, nodeUtilization: 52 },
  { timestamp: '20:00', cpuUtilization: 37, memoryUtilization: 43, nodeUtilization: 50 },
];
